### ISSUE TITLE
Errors with building

### ISSUE THREAD

**Issue by taylorh140** [rikkimax/Bin2D#1]
I tried build a simple example with dmd 2.067.1

bin2d MODULENAME.d=Resource_Reference QCUMBER.jpg

GOT: MODULENAME.d

-------------------------------------MAIN.d
import std.stdio;
import Resource_Reference;

void main() {
    string[] FILE_LOCATIONS = outputFilesToFileSystem();
    FILE_LOCATIONS.each!writeln();
## }

dmd MAIN.d MODULENAME.d

MODULENAME.d(20): Error: undefined identifier names, did you mean variable name?
MODULENAME.d(60): Error: cannot implicitly convert expression ("\xff\xd8\xff\xe0 ..... ) of type string to const( ubyte[] )
MODULENAME.d(58): Error: forward reference to variable QCUMBER_jpg

**Comment by rikkimax** [comment]
Correction:

``` D
string[string] outputFilesToFileSystem()
```

**Comment by rikkimax** [comment]
Please confirm and I'll tag

**Comment by taylorh140** [comment]
Seems to work! of course I had to change my main to match type as well.

import std.stdio;
import Resource_Reference;

void main() {
    string[string] FILE_LOCATIONS = outputFilesToFileSystem();
    FILE_LOCATIONS.writeln();
}

However I am still getting:
MODULENAME.d(29): Deprecation: alias Resource_Reference.outputBin2D2FS is deprecated - Use outputFilesToFileSystem instead
Which I don't believe should be showing up with the setup above. But it does indeed work. Its a very slick tool, thank you.
