### ISSUE TITLE
File name spaces don't seem to be handled.

### ISSUE THREAD

**Issue by taylorh140** [rikkimax/Bin2D#2]
|-------------------------------------|
|               REPORT                |
|------------------|------------------|
|    QCUMBER.jpg    |    QCUMBER_jpg    |
|     tk86t.dll     |     tk86t_dll     |
|     tcl86t.dll    |     tcl86t_dll    |
|  taylor's app.exe |  taylor's app_exe |
|------------------|------------------|

dmd MAIN.d MODULENAME.d

MODULENAME.d(57): Error: unterminated character constant
MODULENAME.d(57): Error: semicolon expected, not '63U'
MODULENAME.d(57): Error: declaration expected, not '63U'
MODULENAME.d(62): Error: unterminated character constant
MODULENAME.d(62): Error: comma expected separating array initializers, not 63U
MODULENAME.d(62): Error: semicolon expected, not 'app_exe'
MODULENAME.d(62): Error: no identifier for declarator app_exe
MODULENAME.d(62): Error: declaration expected, not ']'

Renaming taylor's app.exe to APP.exe fixes this problem.

**Comment by rikkimax** [comment]
There's been a bit of a rewrite of some parts.
But this should definitely not be an issue now.
Please let me know how you feel about __ctfeValues for CTFE access of values when --useEnum is given.

**Comment by taylorh140** [comment]
Things seem to work!
